### ISSUE TITLE
Suggestion: Break blocks.

### ISSUE THREAD

**Issue by sallonium** [vs-marshall/Chione#1]
I really appreciate this project, it would be much greater and OP if you add the option to "Break Blocks", which is i believe when the cursor is pointed at a breakable block at a certain distance (reachable distance like 1-4 blocks) the left mouse autoclicker stops.
Or if you can't bother to do that then would you just give me the instructions and I will do it locally myself,

Great work and Thanks <3

Edit: also I thought this wasn't important enough to mention but I would do it as a sort of feedback or an improvement.
There's quite a simple bug or glitch where sometimes hotkeys stop working untill you restart the client and sometimes you'd have to restart both the client and minecraft. Again this doesn't happen that much for me and i'm not bothered by it but if you wanted to take a look at it then would be kewl.

**Comment by LennardFe** [comment]
Thanks for the nice words, ill take a look and see if i can implement a "Break Blocks" option. Regarding the bug, that hotkeys are not working, are you using the newest 0.1.6 version? Additionally, is there a consistent method to reproduce this bug, such as specific behaviors that occasionally trigger this error?

**Comment by sallonium** [comment]
Yes I am using the newest 0.1.6 version, I have noticed something that could be the reason behind this bug which is when you launch the client BEFORE launching minecraft, after a while the hotkeys just stop indicating even if you try reassigning them they simply don't indicate. This is what i can say.

**Comment by LennardFe** [comment]
Alright, thanks for the details. I've never experienced such a bug, but I'll try to figure it out as soon as I've got some more time. Could you maybe create a config file with the settings you're using when the error happens? That way, I could maybe reproduce this with the same settings as you. 

Are you using Windows 10 or 11?

**Comment by LennardFe** [comment]
Bug fixed and improvements added in the latest 0.1.7 update.
